//
//  ProStylin.swift
//  TapHorse
//
//  Created by Kevin Sullivan on 11/27/16.
//  Copyright © 2016 SideApps. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class ProStylin : NSObject {

    //// Drawing Methods

    public dynamic class func drawCircle(circleScale: CGFloat = 1) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!

        //// Color Declarations
        let color = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Oval Drawing
        context.saveGState()
        context.translateBy(x: 75, y: 75)
        context.scaleBy(x: circleScale, y: circleScale)

        let ovalPath = UIBezierPath(ovalIn: CGRect(x: -72, y: -72, width: 144, height: 144))
        color.setStroke()
        ovalPath.lineWidth = 1
        ovalPath.lineCapStyle = .round
        ovalPath.lineJoinStyle = .round
        ovalPath.stroke()

        context.restoreGState()
    }

}
